version: '3'
services:
  door_sensors:
    container_name: door_sensors
    env_file: .env
    build:
      context: .
      dockerfile: build/Dockerfile
    privileged: true
    volumes:
      - ./worker:/app/worker
    restart: always