version: '3'
services:
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: build/Dockerfile
    privileged: true
    volumes:
      - ./data:/app/data
      - ./worker:/app/worker
    restart: always
    networks:
      - monitoring

  mqtt:
    container_name: mqtt
    restart: always
    image: eclipse-mosquitto:latest
    env_file: .env
    ports:
      - "1883:1883"
      - "9001:9001" #Websockets
    volumes:
      - ./mosquitto/entrypoint.sh:/entrypoint.sh:ro
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/passwords.txt:/mosquitto/config/passwords.txt
      - mosquitto_data:/mosquitto/data:rw
      - mosquitto_log:/mosquitto/log:rw
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    networks:
      - monitoring

volumes:
  mosquitto_data:
  mosquitto_log:
