version: '3'

services:
  worker:
    container_name: worker
    build:
      context: .
      dockerfile: build/Dockerfile
    privileged: true
    volumes:
      - ./data:/app/data
      - ./worker:/app/worker
    depends_on:
      - mosquitto
    restart: always

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    env_file:
      - .env
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
      - ./mosquitto/entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: always


